SUPPORT_LANGUAGES = {
    "en": {
        "ar": "Arabic",
        "zh-CN": "Chinese",
        "en": "English",
        "fr": "French",
        "de": "German",
        "it": "Italian",
        "ja": "Japanese",
        "kk": "Kazakh",
        "ko": "Korean",
        "fa": "Persian",
        "ru": "Russian",
        "es": "Spanish",
        "tr": "Turkish",
        "uk": "Ukrainian",
        "uz": "Uzbek",
    },
    "ru": {
        "ar": "Арабский",
        "zh-CN": "Китайский",
        "en": "Английский",
        "fr": "Французский",
        "de": "Немецкий",
        "it": "Итальянский",
        "ja": "Японский",
        "kk": "Казахский",
        "ko": "Корейский",
        "fa": "Персидский",
        "ru": "Русский",
        "es": "Испанский",
        "tr": "Турецкий",
        "uk": "Украинский",
        "uz": "Узбекский",
    },
}
